# Generated by Django 6.0.6 on 2026-06-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Winner', max_length=100)),
                ('prize_amount', models.IntegerField(default=0)),
                ('winning_date', models.DateField(default='2026-01-01')),
            ],
        ),
    ]
