# Generated by Django 6.0.6 on 2026-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winner',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='winner',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='winner_proofs/'),
        ),
    ]
