# Generated by Django 6.0.6 on 2026-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0002_winner_is_verified_winner_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='winner',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
