# Generated by Django 6.0.6 on 2026-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('number3', models.IntegerField()),
                ('number4', models.IntegerField()),
                ('number5', models.IntegerField()),
                ('draw_type', models.CharField(choices=[('random', 'Random'), ('algorithm', 'Algorithm')], default='random', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
