# Generated by Django 6.0.6 on 2026-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_prizepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='is_simulation',
            field=models.BooleanField(default=True),
        ),
    ]
